"""add_faculty_profile_fields

Revision ID: 180d8597a246
Revises: ed0877622267
Create Date: 2026-06-12 10:00:21.508589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '180d8597a246'
down_revision: Union[str, None] = 'ed0877622267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fp_columns = {c['name'] for c in inspector.get_columns('faculty_profiles')}
    fr_columns = {c['name'] for c in inspector.get_columns('faculty_research')}

    def add_fp_column(name, column):
        if name not in fp_columns:
            op.add_column('faculty_profiles', column)

    def add_fr_column(name, column):
        if name not in fr_columns:
            op.add_column('faculty_research', column)

    add_fp_column('employee_code', sa.Column('employee_code', sa.String(length=64), nullable=True))
    add_fp_column('gender', sa.Column('gender', sa.String(length=16), nullable=True))
    add_fp_column('date_of_birth', sa.Column('date_of_birth', sa.Date(), nullable=True))
    add_fp_column('blood_group', sa.Column('blood_group', sa.String(length=16), nullable=True))
    add_fp_column('marital_status', sa.Column('marital_status', sa.String(length=32), nullable=True))
    add_fp_column('nationality', sa.Column('nationality', sa.String(length=64), nullable=True))
    add_fp_column('alternate_phone', sa.Column('alternate_phone', sa.String(length=32), nullable=True))
    add_fp_column('personal_email', sa.Column('personal_email', sa.String(length=255), nullable=True))
    add_fp_column('current_address', sa.Column('current_address', sa.String(length=512), nullable=True))
    add_fp_column('permanent_address', sa.Column('permanent_address', sa.String(length=512), nullable=True))
    add_fp_column('city', sa.Column('city', sa.String(length=128), nullable=True))
    add_fp_column('state', sa.Column('state', sa.String(length=128), nullable=True))
    add_fp_column('pincode', sa.Column('pincode', sa.String(length=16), nullable=True))
    add_fp_column('profile_photo_url', sa.Column('profile_photo_url', sa.String(length=512), nullable=True))
    add_fp_column('faculty_type', sa.Column('faculty_type', sa.String(length=64), nullable=True))
    add_fp_column('employment_category', sa.Column('employment_category', sa.String(length=64), nullable=True))
    add_fp_column('date_of_joining', sa.Column('date_of_joining', sa.Date(), nullable=True))
    add_fp_column('employment_status', sa.Column('employment_status', sa.String(length=64), nullable=True))
    add_fp_column('approval_status', sa.Column('approval_status', sa.String(length=64), server_default='APPROVED', nullable=False))
    add_fp_column('reporting_hod_id', sa.Column('reporting_hod_id', sa.String(length=36), nullable=True))
    add_fp_column('reporting_principal_id', sa.Column('reporting_principal_id', sa.String(length=36), nullable=True))
    add_fp_column('confirmation_date', sa.Column('confirmation_date', sa.Date(), nullable=True))
    add_fp_column('educational_qualifications', sa.Column('educational_qualifications', sa.JSON(), nullable=True))
    add_fp_column('experience_details', sa.Column('experience_details', sa.JSON(), nullable=True))
    add_fp_column('academic_responsibilities', sa.Column('academic_responsibilities', sa.JSON(), nullable=True))
    add_fp_column('certifications_achievements', sa.Column('certifications_achievements', sa.JSON(), nullable=True))
    add_fp_column('promotion_history', sa.Column('promotion_history', sa.JSON(), nullable=True))
    add_fp_column('increment_history', sa.Column('increment_history', sa.JSON(), nullable=True))
    add_fp_column('documents_repository', sa.Column('documents_repository', sa.JSON(), nullable=True))
    add_fp_column('notification_preferences', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    add_fr_column('publisher', sa.Column('publisher', sa.String(length=255), nullable=True))
    add_fr_column('publication_date', sa.Column('publication_date', sa.Date(), nullable=True))
    add_fr_column('isbn_issn', sa.Column('isbn_issn', sa.String(length=64), nullable=True))
    add_fr_column('research_type', sa.Column('research_type', sa.String(length=64), nullable=True))

    with op.batch_alter_table('faculty_research', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=32),
                   type_=sa.String(length=64),
                   existing_nullable=False)
        batch_op.alter_column('comments',
                   existing_type=sa.VARCHAR(length=1024),
                   type_=sa.String(length=512),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faculty_research', 'comments',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('faculty_research', 'status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('faculty_research', 'research_type')
    op.drop_column('faculty_research', 'isbn_issn')
    op.drop_column('faculty_research', 'publication_date')
    op.drop_column('faculty_research', 'publisher')
    op.drop_column('faculty_profiles', 'notification_preferences')
    op.drop_column('faculty_profiles', 'documents_repository')
    op.drop_column('faculty_profiles', 'increment_history')
    op.drop_column('faculty_profiles', 'promotion_history')
    op.drop_column('faculty_profiles', 'certifications_achievements')
    op.drop_column('faculty_profiles', 'academic_responsibilities')
    op.drop_column('faculty_profiles', 'experience_details')
    op.drop_column('faculty_profiles', 'educational_qualifications')
    op.drop_column('faculty_profiles', 'confirmation_date')
    op.drop_column('faculty_profiles', 'reporting_principal_id')
    op.drop_column('faculty_profiles', 'reporting_hod_id')
    op.drop_column('faculty_profiles', 'approval_status')
    op.drop_column('faculty_profiles', 'employment_status')
    op.drop_column('faculty_profiles', 'date_of_joining')
    op.drop_column('faculty_profiles', 'employment_category')
    op.drop_column('faculty_profiles', 'faculty_type')
    op.drop_column('faculty_profiles', 'profile_photo_url')
    op.drop_column('faculty_profiles', 'pincode')
    op.drop_column('faculty_profiles', 'state')
    op.drop_column('faculty_profiles', 'city')
    op.drop_column('faculty_profiles', 'permanent_address')
    op.drop_column('faculty_profiles', 'current_address')
    op.drop_column('faculty_profiles', 'personal_email')
    op.drop_column('faculty_profiles', 'alternate_phone')
    op.drop_column('faculty_profiles', 'nationality')
    op.drop_column('faculty_profiles', 'marital_status')
    op.drop_column('faculty_profiles', 'blood_group')
    op.drop_column('faculty_profiles', 'date_of_birth')
    op.drop_column('faculty_profiles', 'gender')
    op.drop_column('faculty_profiles', 'employee_code')
    # ### end Alembic commands ###
