"""add_basic_salary_to_pf_configurations

Revision ID: 1a40b9f0b4be
Revises: dad7b9bf3488
Create Date: 2026-06-08 16:27:14.280045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a40b9f0b4be'
down_revision: Union[str, None] = 'dad7b9bf3488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add basic_salary column to pf_configurations with default 0
    op.add_column('pf_configurations', sa.Column(
        'basic_salary',
        sa.Numeric(precision=12, scale=2),
        nullable=False,
        server_default='0'
    ))
    # Remove the server default after column is created (keep default in ORM layer)
    op.alter_column('pf_configurations', 'basic_salary', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pf_configurations', 'basic_salary')
    op.create_table('Faculty',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'FACULTY_MANAGER', 'ASSIGNER', 'FACULTY', name='Role'), server_default=sa.text('\'FACULTY\'::"Role"'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Faculty_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('Faculty_email_key', 'Faculty', ['email'], unique=True)
    op.create_table('Assignment',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dueDate', postgresql.TIMESTAMP(precision=3), autoincrement=False, nullable=False),
    sa.Column('facultyId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='AssignmentStatus'), server_default=sa.text('\'PENDING\'::"AssignmentStatus"'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facultyId'], ['Faculty.id'], name='Assignment_facultyId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='Assignment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('WorkloadLog',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assignmentId', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hoursSpent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('loggedAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(precision=3), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignmentId'], ['Assignment.id'], name='WorkloadLog_assignmentId_fkey', onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='WorkloadLog_pkey')
    )
    op.create_table('faculty_assignments',
    sa.Column('timetable_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('section_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('workload_hours', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name='fk_faculty_assignments_assigned_by_users'),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_faculty_assignments_faculty_id_users'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='fk_faculty_assignments_section_id_sections'),
    sa.ForeignKeyConstraint(['subject_id'], ['courses.id'], name='fk_faculty_assignments_subject_id_courses'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name='fk_faculty_assignments_timetable_id_timetable', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='pk_faculty_assignments')
    )
    # ### end Alembic commands ###
