"""add_basic_salary_to_pf_configurations

Revision ID: 1a40b9f0b4be
Revises: dad7b9bf3488
Create Date: 2026-06-08 16:27:14.280045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a40b9f0b4be'
down_revision: Union[str, None] = 'dad7b9bf3488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = {c['name'] for c in inspector.get_columns('pf_configurations')}
    if 'basic_salary' not in existing_columns:
        # Add basic_salary column to pf_configurations with default 0
        op.add_column('pf_configurations', sa.Column(
            'basic_salary',
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            server_default='0'
        ))
        # Remove the server default after column is created (keep default in ORM layer).
        # SQLite cannot ALTER COLUMN; leaving the '0' server default there is harmless.
        if bind.dialect.name != 'sqlite':
            op.alter_column('pf_configurations', 'basic_salary', server_default=None)


def downgrade() -> None:
    # NOTE: the original autogenerated downgrade() here also re-created a set of
    # unrelated legacy Prisma tables (Faculty/Assignment/WorkloadLog/faculty_assignments)
    # that this migration never dropped. That was autogenerate noise and made the
    # downgrade destructive/incorrect. The real inverse of this migration is a single
    # column drop.
    op.drop_column('pf_configurations', 'basic_salary')
