"""add substitution models

Revision ID: 22fdcf152b35
Revises: ed0877622267
Create Date: 2026-06-10 14:28:36.557519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22fdcf152b35'
down_revision: Union[str, None] = 'ed0877622267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Check and create substitution_status enum
    res_status = bind.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'substitution_status'")).fetchone()
    if not res_status:
        bind.execute(sa.text("CREATE TYPE substitution_status AS ENUM ('PENDING', 'ALLOCATED', 'COMPLETED', 'PARTIALLY_COMPLETED', 'NOT_CONDUCTED')"))
        
    # Check and create allocation_method enum
    res_method = bind.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'allocation_method'")).fetchone()
    if not res_method:
        bind.execute(sa.text("CREATE TYPE allocation_method AS ENUM ('MANUAL', 'AUTOMATIC')"))

    op.create_table('faculty_absences',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_faculty_absences_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faculty_absences'))
    )
    op.create_table('messages',
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_messages_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('publication_plans',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('journal_conference', sa.String(length=255), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_publication_plans_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_plans'))
    )
    op.create_table('research_compliance',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_name', sa.String(length=255), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_research_compliance_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_compliance'))
    )
    op.create_table('substitution_allocations',
    sa.Column('absence_id', sa.String(length=36), nullable=False),
    sa.Column('timetable_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('substitute_faculty_id', sa.String(length=36), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ALLOCATED', 'COMPLETED', 'PARTIALLY_COMPLETED', 'NOT_CONDUCTED', name='substitution_status', create_type=False), nullable=False),
    sa.Column('allocation_method', postgresql.ENUM('MANUAL', 'AUTOMATIC', name='allocation_method', create_type=False), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['absence_id'], ['faculty_absences.id'], name=op.f('fk_substitution_allocations_absence_id_faculty_absences')),
    sa.ForeignKeyConstraint(['substitute_faculty_id'], ['users.id'], name=op.f('fk_substitution_allocations_substitute_faculty_id_users')),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_substitution_allocations_timetable_id_timetable')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_substitution_allocations'))
    )
    
    # Check and add faculty_research columns
    research_cols = [c['name'] for c in inspector.get_columns('faculty_research')]
    if 'proof_file_url' not in research_cols:
        op.add_column('faculty_research', sa.Column('proof_file_url', sa.String(length=512), nullable=True))
    if 'status' not in research_cols:
        op.add_column('faculty_research', sa.Column('status', sa.String(length=32), nullable=False, server_default='PENDING'))
    if 'comments' not in research_cols:
        op.add_column('faculty_research', sa.Column('comments', sa.String(length=1024), nullable=True))
        
    # Check and add study_materials columns
    materials_cols = [c['name'] for c in inspector.get_columns('study_materials')]
    if 'status' not in materials_cols:
        op.add_column('study_materials', sa.Column('status', sa.String(length=32), nullable=False, server_default='PENDING'))
    if 'comments' not in materials_cols:
        op.add_column('study_materials', sa.Column('comments', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_materials', 'comments')
    op.drop_column('study_materials', 'status')
    op.drop_column('faculty_research', 'comments')
    op.drop_column('faculty_research', 'status')
    op.drop_column('faculty_research', 'proof_file_url')
    op.drop_table('substitution_allocations')
    op.drop_table('research_compliance')
    op.drop_table('publication_plans')
    op.drop_table('messages')
    op.drop_table('faculty_absences')
    # ### end Alembic commands ###
