"""add working day config table

Revision ID: 25a299395265
Revises: e62cebe65bf3
Create Date: 2026-06-12 13:20:59.236629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25a299395265'
down_revision: Union[str, None] = 'e62cebe65bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_day_config',
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_working_days', sa.Integer(), nullable=False),
    sa.Column('overrides_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_working_day_config')),
    sa.UniqueConstraint('month', 'year', name='uq_working_day_config_month_year')
    )
    op.add_column('salary', sa.Column('total_working_days', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary', 'total_working_days')
    op.drop_table('working_day_config')
    # ### end Alembic commands ###
