"""Add backup models

Revision ID: 4f047b6c641c
Revises: 20260603_0001
Create Date: 2026-06-06 14:12:47.274042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.migration_guards import has_table

# revision identifiers, used by Alembic.
revision: str = '4f047b6c641c'
down_revision = '25e8f96d5925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not has_table('backup_configurations'):
        op.create_table('backup_configurations',
        sa.Column('auto_backup_enabled', sa.Boolean(), nullable=False),
        sa.Column('schedule_time', sa.String(length=5), nullable=False),
        sa.Column('retention_count', sa.Integer(), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_configurations'))
        )
    if not has_table('backup_history'):
        op.create_table('backup_history',
        sa.Column('filename', sa.String(length=255), nullable=False),
        sa.Column('filepath', sa.String(length=1000), nullable=False),
        sa.Column('size_bytes', sa.BigInteger(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('trigger_type', sa.String(length=50), nullable=False),
        sa.Column('created_by', sa.String(length=36), nullable=True),
        sa.Column('error_message', sa.String(length=4000), nullable=True),
        sa.Column('is_incremental', sa.Boolean(), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_backup_history_created_by_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_history'))
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_history')
    op.drop_table('backup_configurations')
    # ### end Alembic commands ###
