"""add_leave_management_tables

Revision ID: 58257314f31c
Revises: 180d8597a246
Create Date: 2026-06-12 10:06:24.177772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58257314f31c'
down_revision: Union[str, None] = '180d8597a246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_balances',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('casual_leave', sa.Float(), nullable=False),
    sa.Column('sick_leave', sa.Float(), nullable=False),
    sa.Column('earned_leave', sa.Float(), nullable=False),
    sa.Column('on_duty_leave', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leave_balances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_balances')),
    sa.UniqueConstraint('user_id', name=op.f('uq_leave_balances_user_id'))
    )
    op.add_column('leaves', sa.Column('num_days', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('leaves', sa.Column('emergency_contact', sa.String(length=32), nullable=False, server_default='9999999999'))
    op.add_column('leaves', sa.Column('attachment_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaves', 'attachment_url')
    op.drop_column('leaves', 'emergency_contact')
    op.drop_column('leaves', 'num_days')
    op.drop_table('leave_balances')
    # ### end Alembic commands ###
