"""sync_substitutions_and_status

Revision ID: 5904bfd0e404
Revises: ed0877622267
Create Date: 2026-06-10 12:45:06.048808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""sync_substitutions_and_status

Revision ID: 5904bfd0e404
Revises: ed0877622267
Create Date: 2026-06-10 12:45:06.048808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5904bfd0e404'
down_revision: Union[str, None] = 'ed0877622267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_absences',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_faculty_absences_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faculty_absences'))
    )
    op.create_table('messages',
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_messages_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('publication_plans',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('journal_conference', sa.String(length=255), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_publication_plans_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_plans'))
    )
    op.create_table('research_compliance',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_name', sa.String(length=255), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_research_compliance_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_compliance'))
    )
    op.create_table('substitution_allocations',
    sa.Column('absence_id', sa.String(length=36), nullable=False),
    sa.Column('timetable_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('substitute_faculty_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ALLOCATED', 'COMPLETED', 'PARTIALLY_COMPLETED', 'NOT_CONDUCTED', name='substitution_status'), nullable=False),
    sa.Column('allocation_method', sa.Enum('MANUAL', 'AUTOMATIC', name='allocation_method'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['absence_id'], ['faculty_absences.id'], name=op.f('fk_substitution_allocations_absence_id_faculty_absences')),
    sa.ForeignKeyConstraint(['substitute_faculty_id'], ['users.id'], name=op.f('fk_substitution_allocations_substitute_faculty_id_users')),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name=op.f('fk_substitution_allocations_timetable_id_timetable')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_substitution_allocations'))
    )

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    def safe_drop_table(table_name):
        if table_name in tables:
            op.drop_table(table_name)

    def safe_drop_column(table_name, col_name):
        if table_name in tables:
            cols = [c['name'] for c in inspector.get_columns(table_name)]
            if col_name in cols:
                op.drop_column(table_name, col_name)

    def safe_add_column(table_name, column_obj):
        if table_name in tables:
            cols = [c['name'] for c in inspector.get_columns(table_name)]
            if column_obj.name not in cols:
                op.add_column(table_name, column_obj)

    safe_drop_table('pf_contributions')
    safe_drop_table('salary_slip_requests')
    safe_drop_table('pf_claims')
    safe_drop_table('pf_audit_logs')
    safe_drop_table('pf_historical_periods')
    safe_drop_table('pf_leave_exclusions')
    safe_drop_table('pf_configurations')

    for col in [
        'pincode', 'increment_history', 'employment_status', 'city', 'date_of_joining',
        'profile_photo_url', 'experience_details', 'current_address', 'date_of_birth',
        'state', 'promotion_history', 'educational_qualifications', 'notification_preferences',
        'certifications_achievements', 'faculty_type', 'employment_category', 'reporting_hod_id',
        'blood_group', 'confirmation_date', 'permanent_address', 'documents_repository',
        'marital_status', 'academic_responsibilities', 'gender', 'nationality', 'employee_code',
        'reporting_principal_id', 'alternate_phone', 'personal_email'
    ]:
        safe_drop_column('faculty_profiles', col)

    safe_add_column('faculty_research', sa.Column('proof_file_url', sa.String(length=512), nullable=True))
    safe_add_column('faculty_research', sa.Column('status', sa.String(length=32), nullable=False, server_default='APPROVED'))
    safe_add_column('faculty_research', sa.Column('comments', sa.String(length=1024), nullable=True))

    for col in ['isbn_issn', 'publisher', 'publication_date', 'research_type']:
        safe_drop_column('faculty_research', col)

    for col in ['metadata', 'geo_fence_status', 'location_accuracy', 'priority', 'device_network_info', 'app_category', 'session_type']:
        safe_drop_column('leaves', col)

    for col in ['designation', 'joining_date', 'net_salary', 'working_days', 'leave_days', 'leave_deduction', 'employee_id', 'pf_deduction']:
        safe_drop_column('salary', col)

    safe_drop_column('students', 'mentor_id')

    safe_add_column('study_materials', sa.Column('status', sa.String(length=32), nullable=False, server_default='PENDING'))
    safe_add_column('study_materials', sa.Column('comments', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_materials', 'comments')
    op.drop_column('study_materials', 'status')
    op.add_column('students', sa.Column('mentor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('salary', sa.Column('pf_deduction', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
    op.add_column('salary', sa.Column('employee_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('salary', sa.Column('leave_deduction', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
    op.add_column('salary', sa.Column('leave_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('salary', sa.Column('working_days', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=False))
    op.add_column('salary', sa.Column('net_salary', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
    op.add_column('salary', sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('salary', sa.Column('designation', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('session_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('app_category', sa.VARCHAR(length=64), server_default=sa.text("'Leave'::character varying"), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('device_network_info', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('priority', sa.VARCHAR(length=32), server_default=sa.text("'Normal'::character varying"), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('location_accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('geo_fence_status', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('faculty_research', sa.Column('research_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('faculty_research', sa.Column('publication_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('faculty_research', sa.Column('publisher', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('faculty_research', sa.Column('isbn_issn', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('faculty_research', 'comments')
    op.drop_column('faculty_research', 'status')
    op.drop_column('faculty_research', 'proof_file_url')
    op.add_column('faculty_profiles', sa.Column('personal_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('alternate_phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('reporting_principal_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('employee_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('nationality', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('gender', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('academic_responsibilities', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('marital_status', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('documents_repository', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('permanent_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('confirmation_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('blood_group', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('reporting_hod_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('employment_category', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('faculty_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('certifications_achievements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('notification_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('educational_qualifications', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('promotion_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('state', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('current_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('experience_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('profile_photo_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('date_of_joining', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('city', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('employment_status', sa.VARCHAR(length=64), server_default=sa.text("'Active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('increment_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('faculty_profiles', sa.Column('pincode', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.create_table('pf_configurations',
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('pf_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('historical_opening_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('calculation_method', postgresql.ENUM('FIXED', 'PERCENTAGE', name='pf_calculation_method'), autoincrement=False, nullable=False),
    sa.Column('value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('based_on_earned_salary', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('basic_salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_pf_configurations_faculty_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_pf_configurations'),
    sa.UniqueConstraint('faculty_id', name='uq_pf_configurations_faculty_id')
    )
    op.create_table('pf_leave_exclusions',
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('from_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('to_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_pf_leave_exclusions_faculty_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_pf_leave_exclusions')
    )
    op.create_table('pf_historical_periods',
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('from_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('to_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount_per_month', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_pf_historical_periods_faculty_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_pf_historical_periods')
    )
    op.create_table('pf_audit_logs',
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_pf_audit_logs_faculty_id_users'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name='fk_pf_audit_logs_performed_by_users'),
    sa.PrimaryKeyConstraint('id', name='pk_pf_audit_logs')
    )
    op.create_table('pf_claims',
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('claim_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('reference_number', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_pf_claims_faculty_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_pf_claims')
    )
    op.create_table('salary_slip_requests',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remarks', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('admin_remarks', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('salary_slip_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_salary_slip_requests_faculty_id_users'),
    sa.ForeignKeyConstraint(['salary_slip_id'], ['salary_slips.id'], name='fk_salary_slip_requests_salary_slip_id_salary_slips'),
    sa.PrimaryKeyConstraint('id', name='pk_salary_slip_requests')
    )
    op.create_table('pf_contributions',
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('salary_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('employer_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('is_historical', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_pf_contributions_faculty_id_users'),
    sa.ForeignKeyConstraint(['salary_id'], ['salary.id'], name='fk_pf_contributions_salary_id_salary'),
    sa.PrimaryKeyConstraint('id', name='pk_pf_contributions')
    )
    op.drop_table('substitution_allocations')
    op.drop_table('research_compliance')
    op.drop_table('publication_plans')
    op.drop_table('messages')
    op.drop_table('faculty_absences')
    # ### end Alembic commands ###
