"""add_research_tracking_tables

Revision ID: 5d1bb6155b93
Revises: 58257314f31c
Create Date: 2026-06-12 10:57:20.775680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d1bb6155b93'
down_revision: Union[str, None] = '58257314f31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_plans',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('target_journal_conference', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_completion_date', sa.Date(), nullable=False),
    sa.Column('objectives', sa.String(length=1024), nullable=False),
    sa.Column('abstract_summary', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('cycle_start_date', sa.Date(), nullable=False),
    sa.Column('cycle_due_date', sa.Date(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_research_plans_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_plans'))
    )
    op.create_table('publication_proofs',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('journal_name', sa.String(length=255), nullable=False),
    sa.Column('issn_isbn', sa.String(length=64), nullable=False),
    sa.Column('doi_number', sa.String(length=64), nullable=True),
    sa.Column('publication_link', sa.String(length=512), nullable=True),
    sa.Column('proof_file_url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('remarks', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['research_plans.id'], name=op.f('fk_publication_proofs_plan_id_research_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publication_proofs'))
    )
    op.create_table('research_progress_updates',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('progress_date', sa.Date(), nullable=False),
    sa.Column('current_stage', sa.String(length=128), nullable=False),
    sa.Column('percentage_completed', sa.Integer(), nullable=False),
    sa.Column('work_completed', sa.String(length=1024), nullable=False),
    sa.Column('remarks', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['research_plans.id'], name=op.f('fk_research_progress_updates_plan_id_research_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_progress_updates'))
    )
    op.create_table('research_verifications',
    sa.Column('proof_id', sa.String(length=36), nullable=False),
    sa.Column('verified_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('remarks', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proof_id'], ['publication_proofs.id'], name=op.f('fk_research_verifications_proof_id_publication_proofs')),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_research_verifications_verified_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_verifications'))
    )
    op.drop_table('substitution_allocations')
    op.drop_table('messages')
    op.drop_table('faculty_absences')
    op.drop_table('publication_plans')
    op.drop_table('research_compliance')
    op.drop_constraint('fk_students_mentor_id_users', 'students', type_='foreignkey')
    op.drop_column('students', 'emergency_contact_name')
    op.drop_column('students', 'medical_info')
    op.drop_column('students', 'full_name')
    op.drop_column('students', 'father_mobile')
    op.drop_column('students', 'religion')
    op.drop_column('students', 'nationality')
    op.drop_column('students', 'emergency_contact_relationship')
    op.drop_column('students', 'father_occupation')
    op.drop_column('students', 'father_name')
    op.drop_column('students', 'mother_office_address')
    op.drop_column('students', 'mentor_id')
    op.drop_column('students', 'mother_occupation')
    op.drop_column('students', 'passport_number')
    op.drop_column('students', 'skills')
    op.drop_column('students', 'current_address')
    op.drop_column('students', 'emergency_contact_number')
    op.drop_column('students', 'father_email')
    op.drop_column('students', 'hobbies_interests')
    op.drop_column('students', 'community_category')
    op.drop_column('students', 'blood_group')
    op.drop_column('students', 'special_skills')
    op.drop_column('students', 'placement_readiness_score')
    op.drop_column('students', 'mother_email')
    op.drop_column('students', 'father_office_address')
    op.drop_column('students', 'mother_name')
    op.drop_column('students', 'aadhaar_number')
    op.drop_column('students', 'mobile_number')
    op.drop_column('students', 'languages_known')
    op.drop_column('students', 'parent_annual_income')
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'cgpa')
    op.drop_column('students', 'gender')
    op.drop_column('students', 'permanent_address')
    op.drop_column('students', 'mother_mobile')
    op.alter_column('study_materials', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('study_materials', 'comments',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('study_materials', 'comments',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('study_materials', 'status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.add_column('students', sa.Column('mother_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('permanent_address', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('gender', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('parent_annual_income', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('languages_known', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('mobile_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('aadhaar_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('mother_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('father_office_address', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('mother_email', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('placement_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('special_skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('blood_group', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('community_category', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('hobbies_interests', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('father_email', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('emergency_contact_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('current_address', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('passport_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('mother_occupation', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('mentor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('mother_office_address', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('father_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('father_occupation', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('emergency_contact_relationship', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('nationality', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('religion', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('father_mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('full_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('medical_info', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('emergency_contact_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_students_mentor_id_users', 'students', 'users', ['mentor_id'], ['id'])
    op.create_table('research_compliance',
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('requirement_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_research_compliance_faculty_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_research_compliance')
    )
    op.create_table('publication_plans',
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('journal_conference', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_publication_plans_faculty_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_publication_plans')
    )
    op.create_table('faculty_absences',
    sa.Column('faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name='fk_faculty_absences_faculty_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_faculty_absences'),
    postgresql_ignore_search_path=False
    )
    op.create_table('messages',
    sa.Column('sender_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('body', sa.VARCHAR(length=4000), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='fk_messages_receiver_id_users'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='fk_messages_sender_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_messages')
    )
    op.create_table('substitution_allocations',
    sa.Column('absence_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('timetable_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('substitute_faculty_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'ALLOCATED', 'COMPLETED', 'PARTIALLY_COMPLETED', 'NOT_CONDUCTED', name='substitution_status'), autoincrement=False, nullable=False),
    sa.Column('allocation_method', postgresql.ENUM('MANUAL', 'AUTOMATIC', name='allocation_method'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['absence_id'], ['faculty_absences.id'], name='fk_substitution_allocations_absence_id_faculty_absences'),
    sa.ForeignKeyConstraint(['substitute_faculty_id'], ['users.id'], name='fk_substitution_allocations_substitute_faculty_id_users'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetable.id'], name='fk_substitution_allocations_timetable_id_timetable'),
    sa.PrimaryKeyConstraint('id', name='pk_substitution_allocations')
    )
    op.drop_table('research_verifications')
    op.drop_table('research_progress_updates')
    op.drop_table('publication_proofs')
    op.drop_table('research_plans')
    # ### end Alembic commands ###
