"""add_staff_attendance_table

Revision ID: 5eebaa36d735
Revises: e49bbfe58a9b
Create Date: 2026-06-11 14:24:08.765113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eebaa36d735'
down_revision: Union[str, None] = 'e49bbfe58a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'staff_attendance' not in inspector.get_table_names():
        op.create_table('staff_attendance',
        sa.Column('faculty_id', sa.String(length=36), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(length=64), nullable=False),
        sa.Column('check_in', sa.String(length=32), nullable=True),
        sa.Column('check_out', sa.String(length=32), nullable=True),
        sa.Column('working_hours', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('source', sa.String(length=64), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_staff_attendance_faculty_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_attendance'))
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_attendance')
    # ### end Alembic commands ###
