"""add_regulation_quota_to_students

Revision ID: 846e783a199c
Revises: f1d6fedfeb1a
Create Date: 2026-06-09 14:05:18.206700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '846e783a199c'
down_revision: Union[str, None] = 'f1d6fedfeb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c['name'] for c in inspector.get_columns('students')]
    fkeys = inspector.get_foreign_keys('students')
    fkey_names = [fk['name'] for fk in fkeys]

    if 'regulation_id' not in columns:
        op.add_column('students', sa.Column('regulation_id', sa.String(length=36), nullable=True))
    if 'quota' not in columns:
        op.add_column('students', sa.Column('quota', sa.String(length=64), nullable=True))
    
    if 'fk_students_mentor_id_users' in fkey_names or 'students_mentor_id_fkey' in fkey_names:
        fk_name = 'students_mentor_id_fkey' if 'students_mentor_id_fkey' in fkey_names else 'fk_students_mentor_id_users'
        op.drop_constraint(fk_name, 'students', type_='foreignkey')
        
    if 'fk_students_regulation_id_regulations' not in fkey_names:
        op.create_foreign_key(op.f('fk_students_regulation_id_regulations'), 'students', 'regulations', ['regulation_id'], ['id'])
        
    if 'cgpa' in columns:
        op.drop_column('students', 'cgpa')
    if 'mentor_id' in columns:
        op.drop_column('students', 'mentor_id')
    if 'skills' in columns:
        op.drop_column('students', 'skills')
    if 'placement_readiness_score' in columns:
        op.drop_column('students', 'placement_readiness_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('placement_readiness_score', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('mentor_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_students_regulation_id_regulations'), 'students', type_='foreignkey')
    op.create_foreign_key('fk_students_mentor_id_users', 'students', 'users', ['mentor_id'], ['id'])
    op.drop_column('students', 'quota')
    op.drop_column('students', 'regulation_id')
    # ### end Alembic commands ###
