"""Add PF Management tables

Revision ID: dad7b9bf3488
Revises: ed0877622267
Create Date: 2026-06-08 15:56:27.012303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dad7b9bf3488'
down_revision: Union[str, None] = 'ed0877622267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pf_audit_logs',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_pf_audit_logs_faculty_id_users')),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_pf_audit_logs_performed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pf_audit_logs'))
    )
    op.create_table('pf_claims',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_number', sa.String(length=128), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_pf_claims_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pf_claims'))
    )
    op.create_table('pf_configurations',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('pf_start_date', sa.Date(), nullable=False),
    sa.Column('historical_opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('calculation_method', sa.Enum('FIXED', 'PERCENTAGE', name='pf_calculation_method'), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('based_on_earned_salary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_pf_configurations_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pf_configurations')),
    sa.UniqueConstraint('faculty_id', name=op.f('uq_pf_configurations_faculty_id'))
    )
    op.create_table('pf_historical_periods',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('amount_per_month', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_pf_historical_periods_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pf_historical_periods'))
    )
    op.create_table('pf_contributions',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('salary_id', sa.String(length=36), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('employer_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_historical', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_pf_contributions_faculty_id_users')),
    sa.ForeignKeyConstraint(['salary_id'], ['salary.id'], name=op.f('fk_pf_contributions_salary_id_salary')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pf_contributions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pf_contributions')
    op.drop_table('pf_historical_periods')
    op.drop_table('pf_configurations')
    op.drop_table('pf_claims')
    op.drop_table('pf_audit_logs')
    # ### end Alembic commands ###
