"""add_joining_date_to_salary

Revision ID: e49bbfe58a9b
Revises: 7a7b7c7d7e7f
Create Date: 2026-06-09 17:23:51.403879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e49bbfe58a9b'
down_revision: Union[str, None] = '7a7b7c7d7e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_columns = {c['name'] for c in inspector.get_columns('salary')}
    if 'joining_date' not in existing_columns:
        op.add_column('salary', sa.Column('joining_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary', 'joining_date')
    # ### end Alembic commands ###
