"""add_system_setting_history

Revision ID: ed0877622267
Revises: 4f047b6c641c
Create Date: 2026-06-06 15:19:22.589172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed0877622267'
down_revision: Union[str, None] = '4f047b6c641c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting_history',
    sa.Column('setting_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('old_value', sa.String(length=4000), nullable=True),
    sa.Column('new_value', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['setting_id'], ['system_settings.id'], name=op.f('fk_system_setting_history_setting_id_system_settings')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_system_setting_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_setting_history'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_setting_history')
    # ### end Alembic commands ###

