"""add_pf_leave_exclusions

Revision ID: f1d6fedfeb1a
Revises: 1a40b9f0b4be
Create Date: 2026-06-08 16:34:39.936939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1d6fedfeb1a'
down_revision: Union[str, None] = '1a40b9f0b4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pf_leave_exclusions',
    sa.Column('faculty_id', sa.String(length=36), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['users.id'], name=op.f('fk_pf_leave_exclusions_faculty_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pf_leave_exclusions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pf_leave_exclusions')
    # ### end Alembic commands ###

